# Generated by Django 4.2.8 on 2025-06-03 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('shift_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'table_shifts',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=55)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('contact_number', models.CharField(blank=True, max_length=55)),
                ('email', models.EmailField(blank=True, max_length=55)),
                ('username', models.CharField(max_length=55, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.shifts')),
            ],
            options={
                'db_table': 'table_users',
            },
        ),
    ]
